config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :items do
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comments, presence: true

  belongs_to :user
  belongs_to :item
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/item.rb
class Item < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :style_text
    validates :images, :images_type, :images_length
  end

  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  private

  def images_type
    images.each do |image|
      errors.add(:style_image, 'はJPGまたはPNG形式でアップロードしてください') unless image.blob.content_type.in?(%('image/jpeg image/png'))
    end
  end

  def images_length
    if images.length >= 7
      errors.add(:style_image, 'は6枚以内にしてください')
    else
      images.length <= 6
    end
  end

  def self.search(search)
    if search != ''
      Item.where('title LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :nickname, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  has_many :items
  has_many :comments
  has_many :favorites, dependent: :destroy

  def already_favorited?(item)
    favorites.exists?(item_id: item.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configer_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configer_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to item_path(@comment.item)
    else
      @item = @comment.item
      @comments = @item.comments
      render 'items/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comments).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(item_id: params[:item_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:item_id])
    @favorite = current_user.favorites.find_by(item_id: @item.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :access_item, only: [:edit, :update, :destroy]

  def index
    @items = Item.includes(:user).order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments
  end

  def search
    @items = Item.search(params[:keyword])
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @item.destroy
  end

  private

  def item_params
    params.require(:item).permit(:title, :style_text, :outer_item, :tops_item, :bottoms_item, :shoes_item, :goods_item,
                                 images: []).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def access_item
    redirect_to root_path unless @item.user == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary"></strong>
          <h3 class="mb-0"><%= item.title %></h3>
        <% if user_signed_in? %>
          <div class=favorites>
            <% if current_user != item.user %>
              <% if current_user.already_favorited?(item) %>
                  <%= link_to item_favorites_path(item), method: :delete do %>
                    <i class= "fas fa-heart"></i>
                  <% end %>
              <% else %>
                  <%= link_to item_favorites_path(item), method: :post do %>
                      <i class= "far fa-heart"></i>
                  <% end %>
              <% end %>
            <% else %>
              <i class= "far fa-heart"></i>
            <% end %>
            <%= item.favorites.count %>
          </div>
        <% end %>
        <div class="mb-1 text-muted"><%= link_to item.user.nickname, user_path(item.user) %></div>
          <p class="card-text mb-auto"><%= item.style_text %></p>
          <%= link_to "詳細", item_path(item.id) %>
        </div>
        <div class="col-auto d-none d-lg-block">
          <div class="item-images img-fluid">
          <%= image_tag item.images[0], class:'images' %>
          </div>
        </div>
      </div>
    </div>

    
    

app/views/items/edit.html.erb
<%= render "shared/header_item"%>

 
<div class="overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light" >
 <main class="container">
    <div class="py-5 ">
      <h2 class="alert alert-secondary" role="alert">投稿編集画面</h2>
      <p class="lead ">Todays Your Coordination</p>
    </div>
  
  
    <%= form_with model:@item, local: true do |f|%>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-items">
      <div class="col-sm-7"> 
        <%= f.label :title, "Title-タイトル-" %><span class="badge bg-danger">必須</span><br />
        <%= f.text_field :title, class: "mb-3", class: "form-control", id:"title" %>
        <%= f.label :style_text, "Style_text-コーディネート詳細-" %><span class="badge bg-danger">必須</span><br />
        <%= f.text_area :style_text, class: "mb-3", class: "form-control", id: "style_text"%>
        <%= f.label :outer_item, "Outer_item-アウター-" %><br />
        <%= f.text_field :outer_item, class: "mb-3", class: "form-control", id:"outer_item" %>
        <%= f.label :tops_item, "Tops_item-トップス-" %><br />
        <%= f.text_field :tops_item, class: "mb-3", class: "form-control", id:"tops_item" %>
        <%= f.label :bottoms_item, "Bottoms_item-ボトムス-" %><br />
        <%= f.text_field :bottoms_item, class: "mb-3", class: "form-control", id:"bottoms_item" %>
        <%= f.label :shoes_item, "Shoes_item-シューズ-" %><br />
        <%= f.text_field :shoes_item, class: "mb-3", class: "form-control", id:"shoes_item" %>
        <%= f.label :goods_item, "Goods-小物類-" %><br />
        <%= f.text_field :goods_item, class: "mb-3", class: "form-control", id:"goods_item" %>
      </div>

      <div class="col-5">
        <%= f.label :images, "Styling_image-コーディネート画像-" %><span class="badge bg-danger">必須</span><p>(画像は6枚まで投稿できます)</p><br />
        <%= f.file_field :images, multiple: true, name: 'item[images][]', id:"item_image" %>
        <div class="image-list img-fluid" id="image-list">
            <% @item.images.each do |image| %>
            <%= image_tag image, class: 'images' %>
            <% end %>
        </div>
      </div>
    </div>
      <div class="item-btn">
        <%= f.submit "変更する", class: "btn btn-primary btn-lg"%>
    <% end %>
    </div>

 </main>
</div>


<%= render "shared/footer_item"%>

app/views/items/index.html.erb
<%= render "shared/header_item"%>


<main>
<div class= "position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="card bg-light text-white">
  <%= image_tag "22235444_m .jpg", class: "img-fluid"%>
   <div class="card-img-overlay">
    <h1 class="card-title">ー新しいを日常的にー</h1>
    <p class="card-text">あなたのワードローブに新しい、そして日常的な選択肢を</p>
    <p class="card-text">Daily_Wardrobeを使う人に新しい選択肢をそして新しいを日常的に</p>
   </div>
  </div>
</div>
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 bg-light">
<h2 class="alert alert-secondary role=alert text-center">投稿一覧</h2>
<div class="d-md-flex flex-md-equal my-md-3">
  <div class="row mb-2">
  <%= render @items %>
  </div>
</div>
</main>



<%= render "shared/footer_item"%>

app/views/items/new.html.erb
<%= render "shared/header_item"%>

 
<div class="overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light" >
 <main class="container">
    <div class="py-5 ">
      <h2 class="alert alert-secondary" role="alert">投稿画面</h2>
      <p class="lead ">Todays Your Coordination</p>
    </div>
  
  
    <%= form_with model:@item, local: true do |f|%>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-items">
      <div class="col-sm-7"> 
        <%= f.label :title, "Title-タイトル-" %><span class="badge bg-danger">必須</span><br />
        <%= f.text_field :title, class: "mb-3", class: "form-control", id:"title" %>
        <%= f.label :style_text, "Style_text-コーディネート詳細-" %><span class="badge bg-danger">必須</span><br />
        <%= f.text_area :style_text, class: "mb-3", class: "form-control", id: "style_text"%>
        <%= f.label :outer_item, "Outer_item-アウター-" %><br />
        <%= f.text_field :outer_item, class: "mb-3", class: "form-control", id:"outer_item" %>
        <%= f.label :tops_item, "Tops_item-トップス-" %><br />
        <%= f.text_field :tops_item, class: "mb-3", class: "form-control", id:"tops_item" %>
        <%= f.label :bottoms_item, "Bottoms_item-ボトムス-" %><br />
        <%= f.text_field :bottoms_item, class: "mb-3", class: "form-control", id:"bottoms_item" %>
        <%= f.label :shoes_item, "Shoes_item-シューズ-" %><br />
        <%= f.text_field :shoes_item, class: "mb-3", class: "form-control", id:"shoes_item" %>
        <%= f.label :goods_item, "Goods-小物類-" %><br />
        <%= f.text_field :goods_item, class: "mb-3", class: "form-control", id:"goods_item" %>
      </div>

      <div class="col-5">
        <%= f.label :images, "Styling_image-コーディネート画像-" %><span class="badge bg-danger">必須</span><p>(画像は6枚まで投稿できます)</p><br />
        <%= f.file_field :images, multiple: true, name: 'item[images][]', id:"item_image" %>
        <div class="image-list img-fluid" id="image-list">
            <% @item.images.each do |image| %>
            <%= image_tag image, class: 'images' %>
            <% end %>
        </div>
      </div>
    </div>
      <div class="item-btn">
        <%= f.submit "投稿する", class: "btn btn-primary btn-lg"%>
    <% end %>
    </div>

 </main>
</div>


<%= render "shared/footer_item"%>

app/views/items/search.html.erb
<%= render "shared/header_item"%>

<div class="overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light" >
    <div class="py-5 ">
      <h2 class="alert alert-secondary" role="alert">検索結果</h2>
    </div>
    <div class="row mb-2">
      <% @items.each do |item| %>
        <%= render partial: "item", locals: { item: item } %>
      <% end %>
    </div>
</div>

<%= render "shared/footer_item"%>

app/views/items/show.html.erb
<%= render "shared/header_item"%>


<div class="overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light" >
  <div class="inner">
    <div class="item__wrapper">
      <p class="item__hedding">
        <%= @item.title %>
      </p>
      <% if user_signed_in? %>
        <div class=favorites >
          <% if current_user != @item.user %>
              <% if current_user.already_favorited?(@item) %>
                  <%= link_to item_favorites_path(@item), method: :delete do %>
                    <i class= "fas fa-heart"></i>
                  <% end %>
              <% else %>
                  <%= link_to item_favorites_path(@item), method: :post do %>
                      <i class= "far fa-heart"></i>
                  <% end %>
              <% end %>
          <% else %>
            <i class= "far fa-heart"></i>
          <% end %>
              <%= @item.favorites.count %>
        </div>
      <% end %>
      <%= link_to @item.user.nickname, user_path(@item.user), class: :item__user %>
      <% if @item.user == current_user %>
        <div class="item__manage">
          <%= link_to "編集する", edit_item_path(@item.id), class: :item__btn %>
          <%= link_to "削除する", item_path(@item.id), method: :delete, class: :item__btn %>
        </div>
      <% end %>
      <div class="item__images">
      <% @item.images.each do |image| %>
        <%= image_tag image, class: 'images' %>
      <% end %>
      </div>
      <div class="item__body">
        <div class="item__detail">
          <p class="detail__title">Style_text-コーディネート詳細-</p>
          <p class="detail__message">
            <%= @item.style_text %>
          </p>
        </div>
        <div class="item__detail">
          <p class="detail__title">Outer_item-アウター-</p>
          <p class="detail__message">
            <%= @item.outer_item %>
          </p>
        </div>
        <div class="item__detail">
          <p class="detail__title">Tops_item-トップス-</p>
          <p class="detail__message">
            <%= @item.tops_item %>
          </p>
        </div>
        <div class="item__detail">
          <p class="detail__title">Bottoms_item-ボトムス-</p>
          <p class="detail__message">
            <%= @item.bottoms_item %>
          </p>
        </div>
        <div class="item__detail">
          <p class="detail__title">Shoes_item-シューズ-</p>
          <p class="detail__message">
            <%= @item.shoes_item %>
          </p>
        </div>
        <div class="item__detail">
          <p class="detail__title">Goods-小物類-</p>
          <p class="detail__message">
            <%= @item.goods_item %>
          </p>
        </div>
      </div>
      </div>
    </div>
  </div>
  <div class="item__comments p-3 p-md-5 m-md-3 bg-light">
        <% if user_signed_in? %>
          <%= form_with model: [@item,@comment],local: true do |f|%>
            <div class="field">
              <%= f.label :comments, "コメント" %><br />
              <%= f.text_field :comments, id:"comments" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: "btn btn-primary" %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.comments%>
              <%= link_to "(#{comment.user.nickname})", root_path, class: :comments_user %>
            </li>
          <% end %>
        </ul>
  </div>



<%= render "shared/footer_item"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyWardrobe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/3c30869df3.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer_item.html.erb
<footer class="container py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">&copy; 2017-2021</small>
    </div>
    <div class="col-6 col-md">
      <h5>Daily_Wardrobeについて</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">会社概要</a></li>
        <li><a class="link-secondary" href="#">プライバシーポリシー</a></li>
        <li><a class="link-secondary" href="#">利用規約</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Daily_Wardrobeで探す</h5>
      <ul class="list-unstyled text-small">
        <li><a class="link-secondary" href="#">カテゴリ</a></li>
        <li><a class="link-secondary" href="#">アイテム</a></li>
        <li><a class="link-secondary" href="#">投稿者</a></li>
      </ul>
    </div>
    </div>
</footer>

app/views/shared/_header_item.html.erb
<header class="d-flex flex-column h-100">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
    <%= link_to 'Daily_Wardrobe', root_path, class: "navbar-brand"%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div>
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <div class= "lists-right">
                <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |form| %>
                  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
                  <%= form.submit "検索", class: "btn btn-secondary btn-sm" %>
                <% end %>
              <% if user_signed_in? %>
                <li><%= link_to '投稿する', new_item_path, class: "purchase-btn" %></li>
                <li><%= link_to current_user.nickname, user_path(current_user), class: "user-nickname" %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
              <% else %>
                <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
                <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
              <% end %>
          </ul>
        </div>
    </div>
  </nav>
</header>

app/views/users/show.html.erb
<%= render "shared/header_item"%>

<div class="main">
  <div class="inner">
  <div class= "position-relative overflow-hidden p-3 p-md-5 m-md-3 bg-light">
    <div class="user__wrapper">
      <h2 class="page-heading alert alert-secondary role=alert">
        <%= "#{@user.nickname}の投稿"%>
      </h2>
    </div>
  <div class="d-md-flex flex-md-equal my-md-3">
    <div class="row mb-2">
    <%= render partial: "items/item", collection: @user.items %>
    </div>
  </div>
  </div>
</div>


<%= render "shared/footer_item"%>